import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { drawPdfLogo } from './pdfLogo';

export interface InventoryReportRow {
    itemType: 'Raw Material' | 'Finished Good';
    skuCode: string;
    name: string;
    categoryName: string | null;
    locationName: string | null;
    unit: string;
    currentStock: number;
    stockValue: number | null;
    stockLevel: 'Low' | 'Medium' | 'Good';
    status: 'Active' | 'Inactive';
}

export type StockTierKey = 'Good' | 'Medium' | 'Low' | 'Out of Stock';

export interface InventoryReportOptions {
    rows: InventoryReportRow[];
    tierCounts: Record<StockTierKey, number>;
    categoryBreakdown: [string, number][];
    // Hex strings (e.g. '#93c5fd') - same palette as the on-screen donut (dashboardUtils.ts's
    // pieColors), converted to RGB here since jsPDF's fill APIs don't accept hex.
    categoryColors: string[];
    logoDataUrl?: string | null;
    companySettings?: { companyName: string; address: string };
}

const formatRupees = (value: number): string => `Rs. ${value.toLocaleString('en-IN')}`;

const COLOR = {
    navy: [15, 23, 42] as const,
    blue: [37, 99, 235] as const,
    label: [100, 116, 139] as const,
    body: [51, 65, 85] as const,
    muted: [148, 163, 184] as const,
    border: [226, 232, 240] as const,
    white: [255, 255, 255] as const,
    surface: [248, 250, 252] as const,
};

const TIER_COLOR: Record<StockTierKey, { text: readonly [number, number, number]; bg: readonly [number, number, number] }> = {
    Good: { text: [22, 163, 74], bg: [220, 252, 231] },
    Medium: { text: [217, 119, 6], bg: [254, 243, 199] },
    Low: { text: [220, 38, 38], bg: [254, 226, 226] },
    'Out of Stock': { text: [71, 85, 105], bg: [226, 232, 240] },
};

const LEVEL_DOT_COLOR: Record<InventoryReportRow['stockLevel'], readonly [number, number, number]> = {
    Good: [22, 163, 74],
    Medium: [217, 119, 6],
    Low: [220, 38, 38],
};

const MARGIN = 14;
const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const RIGHT_EDGE = PAGE_WIDTH - MARGIN;
const CONTENT_WIDTH = RIGHT_EDGE - MARGIN;
// Single shared baseline for "Generated By" and "Page X of Y" so the two always line up on
// the exact same row instead of drifting apart (or overlapping) depending on how much notes
// content pushed the footer down on a given page.
const FOOTER_TEXT_Y = PAGE_HEIGHT - 14;

function hexToRgb(hex: string): readonly [number, number, number] {
    const clean = hex.replace('#', '');
    const r = parseInt(clean.substring(0, 2), 16);
    const g = parseInt(clean.substring(2, 4), 16);
    const b = parseInt(clean.substring(4, 6), 16);
    return [Number.isFinite(r) ? r : 0, Number.isFinite(g) ? g : 0, Number.isFinite(b) ? b : 0];
}

// A lot of uploaded brand logos carry a chunk of fully-transparent padding baked into the file
// itself (space around the mark left by whatever tool exported it). drawPdfLogo places the
// *raw* image's bounding box flush against the header margin, so that baked-in padding pushes
// the visibly-drawn logo noticeably right of the company name/address text below it, even
// though both are technically "left-aligned" at the same x. This decodes a PNG logo on an
// offscreen canvas, finds the bounding box of its actually-opaque pixels, and returns a
// re-cropped data URL so the *visible* mark - not just the file's raw canvas - lines up with
// the text underneath. Non-PNG images (no alpha channel to inspect) are returned unchanged,
// since there's no safe way to guess where a background "ends" without one.
async function trimTransparentLogoPadding(dataUrl: string): Promise<string> {
    if (!dataUrl.startsWith('data:image/png')) return dataUrl;
    try {
        const img = await new Promise<HTMLImageElement>((resolve, reject) => {
            const image = new Image();
            image.onload = () => resolve(image);
            image.onerror = () => reject(new Error('logo image failed to load'));
            image.src = dataUrl;
        });
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth;
        canvas.height = img.naturalHeight;
        const ctx = canvas.getContext('2d');
        if (!ctx || canvas.width === 0 || canvas.height === 0) return dataUrl;
        ctx.drawImage(img, 0, 0);
        const { data, width, height } = ctx.getImageData(0, 0, canvas.width, canvas.height);

        const ALPHA_THRESHOLD = 10;
        let minX = width;
        let minY = height;
        let maxX = -1;
        let maxY = -1;
        for (let py = 0; py < height; py++) {
            for (let px = 0; px < width; px++) {
                const alpha = data[(py * width + px) * 4 + 3];
                if (alpha > ALPHA_THRESHOLD) {
                    if (px < minX) minX = px;
                    if (px > maxX) maxX = px;
                    if (py < minY) minY = py;
                    if (py > maxY) maxY = py;
                }
            }
        }
        // Fully transparent image, or already tight to its own edges - nothing to trim.
        if (maxX < 0 || (minX === 0 && minY === 0 && maxX === width - 1 && maxY === height - 1)) {
            return dataUrl;
        }

        const trimmedWidth = maxX - minX + 1;
        const trimmedHeight = maxY - minY + 1;
        const trimmedCanvas = document.createElement('canvas');
        trimmedCanvas.width = trimmedWidth;
        trimmedCanvas.height = trimmedHeight;
        const trimmedCtx = trimmedCanvas.getContext('2d');
        if (!trimmedCtx) return dataUrl;
        trimmedCtx.drawImage(canvas, minX, minY, trimmedWidth, trimmedHeight, 0, 0, trimmedWidth, trimmedHeight);
        return trimmedCanvas.toDataURL('image/png');
    } catch {
        // Decode failure (corrupt data, unsupported format, etc.) - fall back to the
        // untrimmed logo rather than breaking PDF export over a cosmetic crop.
        return dataUrl;
    }
}

// drawPdfLogo only returns the rendered WIDTH (it draws the logo inside a maxSize x maxSize
// box but discards the aspect-ratio-derived height once drawn). A wide/short logo - like a
// wordmark - then only occupies a fraction of that box vertically, so blindly reserving the
// full maxSize before stacking the company name below it leaves a large dead gap. This mirrors
// drawPdfLogo's own aspect-ratio math to recover the logo's true rendered height instead.
function getLogoRenderedHeight(doc: jsPDF, logoDataUrl: string | null | undefined, maxSize: number): number {
    if (!logoDataUrl) return 0;
    try {
        const props = doc.getImageProperties(logoDataUrl);
        const ratio = props.width / props.height;
        return ratio >= 1 ? maxSize / ratio : maxSize;
    } catch {
        return 0;
    }
}

// Approximates a filled donut wedge with a fan of thin triangles from the center - jsPDF has
// no native "arc"/"pie slice" primitive, so this is the standard workaround (same trick
// browsers' own canvas-less pie renderers use). ~4deg per triangle is fine-grained enough
// that the wedge edge reads as a smooth curve at print resolution.
function drawDonutWedge(doc: jsPDF, cx: number, cy: number, radius: number, startDeg: number, endDeg: number, color: readonly [number, number, number]): void {
    doc.setFillColor(...color);
    const steps = Math.max(1, Math.ceil((endDeg - startDeg) / 4));
    for (let i = 0; i < steps; i++) {
        const a1 = (startDeg + (endDeg - startDeg) * (i / steps)) * (Math.PI / 180);
        const a2 = (startDeg + (endDeg - startDeg) * ((i + 1) / steps)) * (Math.PI / 180);
        const x1 = cx + radius * Math.cos(a1);
        const y1 = cy + radius * Math.sin(a1);
        const x2 = cx + radius * Math.cos(a2);
        const y2 = cy + radius * Math.sin(a2);
        doc.triangle(cx, cy, x1, y1, x2, y2, 'F');
    }
}

export async function exportInventoryReportPdf(options: InventoryReportOptions): Promise<void> {
    const { rows, tierCounts, categoryBreakdown, categoryColors, logoDataUrl, companySettings } = options;
    // Trimmed once up front so both the image draw and the height math below agree on the
    // same (padding-free) logo - see trimTransparentLogoPadding for why this is needed.
    const trimmedLogoDataUrl = logoDataUrl ? await trimTransparentLogoPadding(logoDataUrl) : logoDataUrl;
    const doc = new jsPDF();

    // ---- Header: logo (top-left, larger) with company name/address stacked directly BELOW
    // it - not beside it, so a bigger logo has room to breathe instead of crowding the text -
    // "INVENTORY REPORT" title + report date on the right. ----
    const logoTop = 12;
    const logoMaxSize = 32;
    const logoWidth = drawPdfLogo(doc, trimmedLogoDataUrl, MARGIN, logoTop, logoMaxSize);
    const logoHeight = getLogoRenderedHeight(doc, trimmedLogoDataUrl, logoMaxSize);

    let leftY = logoTop + (logoWidth ? logoHeight + 10 : 0);
    if (companySettings?.companyName) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        doc.setTextColor(...COLOR.navy);
        doc.text(companySettings.companyName, MARGIN, leftY);
        leftY += 5;
    }
    if (companySettings?.address) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(...COLOR.muted);
        const addrLines = doc.splitTextToSize(companySettings.address, CONTENT_WIDTH / 2);
        doc.text(addrLines, MARGIN, leftY);
        leftY += addrLines.length * 4;
    }

    let y = 20;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(...COLOR.blue);
    doc.text('INVENTORY REPORT', RIGHT_EDGE, y, { align: 'right' });

    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(...COLOR.label);
    doc.text(`Report Date: ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}`, RIGHT_EDGE, y, { align: 'right' });

    y = Math.max(leftY, y) + 8;
    doc.setDrawColor(...COLOR.border);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, RIGHT_EDGE, y);
    y += 10;

    // ---- Stock Overview (donut) + Stock Level Distribution, side by side ----
    const overviewTop = y;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(...COLOR.blue);
    doc.text('STOCK OVERVIEW', MARGIN, y);

    const donutCx = MARGIN + 20;
    const donutCy = y + 30;
    const donutRadius = 18;
    const totalItems = rows.length;
    let angleCursor = -90;
    categoryBreakdown.forEach(([, count], index) => {
        const sweep = totalItems > 0 ? (count / totalItems) * 360 : 0;
        drawDonutWedge(doc, donutCx, donutCy, donutRadius, angleCursor, angleCursor + sweep, hexToRgb(categoryColors[index % categoryColors.length]));
        angleCursor += sweep;
    });
    doc.setFillColor(...COLOR.white);
    doc.circle(donutCx, donutCy, donutRadius * 0.62, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.setTextColor(...COLOR.navy);
    doc.text(String(totalItems), donutCx, donutCy - 1, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...COLOR.muted);
    doc.text('Total Items', donutCx, donutCy + 4.5, { align: 'center' });

    let legendY = y + 14;
    const legendX = donutCx + donutRadius + 10;
    categoryBreakdown.slice(0, 6).forEach(([label, count], index) => {
        const percent = totalItems > 0 ? Math.round((count / totalItems) * 100) : 0;
        doc.setFillColor(...hexToRgb(categoryColors[index % categoryColors.length]));
        doc.rect(legendX, legendY - 3, 3, 3, 'F');
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(...COLOR.body);
        doc.text(`${label}  ${count} (${percent}%)`, legendX + 5, legendY);
        legendY += 6;
    });

    const overviewColWidth = CONTENT_WIDTH * 0.42;
    const tierColX = MARGIN + overviewColWidth + 8;
    const tierColWidth = CONTENT_WIDTH - overviewColWidth - 8;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(...COLOR.blue);
    doc.text('STOCK LEVEL DISTRIBUTION', tierColX, overviewTop);

    const tiers: StockTierKey[] = ['Good', 'Medium', 'Low', 'Out of Stock'];
    const tierCardWidth = (tierColWidth - 9) / 2;
    const tierCardHeight = 26;
    tiers.forEach((tier, index) => {
        const col = index % 2;
        const row = Math.floor(index / 2);
        const cardX = tierColX + col * (tierCardWidth + 9);
        const cardY = overviewTop + 6 + row * (tierCardHeight + 6);
        const style = TIER_COLOR[tier];
        const count = tierCounts[tier];
        const percent = totalItems > 0 ? Math.round((count / totalItems) * 100) : 0;

        doc.setDrawColor(...COLOR.border);
        doc.setLineWidth(0.2);
        doc.roundedRect(cardX, cardY, tierCardWidth, tierCardHeight, 2, 2, 'S');

        doc.setFillColor(...style.bg);
        doc.circle(cardX + 6, cardY + 6.5, 3.2, 'F');

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(...COLOR.label);
        doc.text(tier === 'Good' ? 'High (Good)' : tier, cardX + 12, cardY + 5.5);

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(13);
        doc.setTextColor(...style.text);
        doc.text(`${percent}%`, cardX + 4, cardY + 14);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(...COLOR.muted);
        doc.text(`${count} Items`, cardX + 4, cardY + 18.5);

        doc.setFillColor(...COLOR.border);
        doc.roundedRect(cardX + 4, cardY + 21, tierCardWidth - 8, 1.4, 0.7, 0.7, 'F');
        if (percent > 0) {
            doc.setFillColor(...style.text);
            doc.roundedRect(cardX + 4, cardY + 21, Math.max(2, (tierCardWidth - 8) * (percent / 100)), 1.4, 0.7, 0.7, 'F');
        }
    });

    y = Math.max(legendY + 6, overviewTop + 6 + 2 * (tierCardHeight + 6)) + 4;

    // ---- Items table ----
    autoTable(doc, {
        startY: y,
        margin: { left: MARGIN, right: MARGIN, bottom: 20 },
        head: [['Type', 'SKU Code', 'Name', 'Category', 'Location', 'Current Stock', 'Stock Value', 'Stock Level', 'Status']],
        body: rows.map((row) => [
            row.itemType,
            row.skuCode,
            row.name,
            row.categoryName ?? '—',
            row.locationName ?? '—',
            `${row.currentStock} ${row.unit}`,
            row.stockValue === null ? '—' : formatRupees(row.stockValue),
            // Stock Level / Status are left blank here on purpose - they're fully hand-drawn
            // (dot+text / pill+text) in didDrawCell below. Leaving the real text in the body
            // meant autoTable rendered it AND didDrawCell drew over it, producing the
            // overlapping/doubled text in those two columns.
            '',
            '',
        ]),
        theme: 'plain',
        // overflow defaults to 'linebreak' here (NOT 'ellipsize') - a long SKU name or address
        // wraps onto a second line instead of being cut off with "…", so the real value always
        // stays visible. Every column below gets an explicit width (summing to the full
        // CONTENT_WIDTH) sized for its typical content, so wrapping is the exception rather
        // than the norm.
        styles: { fontSize: 7.5, textColor: [...COLOR.body], cellPadding: { top: 3, bottom: 3, left: 2.5, right: 2.5 }, valign: 'middle' },
        headStyles: {
            fillColor: [...COLOR.surface],
            textColor: [...COLOR.navy],
            fontStyle: 'bold',
            fontSize: 7.5,
            lineWidth: { bottom: 0.3 },
            lineColor: [...COLOR.border],
        },
        bodyStyles: { lineWidth: { bottom: 0.1 }, lineColor: [...COLOR.border] },
        columnStyles: {
            0: { cellWidth: 20 },
            1: { cellWidth: 17 },
            2: { cellWidth: 30 },
            3: { cellWidth: 17 },
            4: { cellWidth: 26 },
            5: { cellWidth: 17 },
            6: { cellWidth: 19 },
            7: { cellWidth: 19 },
            8: { cellWidth: 17 },
        },
        // Draws a small colored dot before the Stock Level text and a colored pill behind the
        // Status text - autoTable's plain body array can't carry per-cell color, so both are
        // hand-drawn here instead of via the cell's text content.
        didDrawCell: (data) => {
            if (data.section !== 'body') return;
            const row = rows[data.row.index];
            if (!row) return;
            if (data.column.index === 7) {
                const dotColor = LEVEL_DOT_COLOR[row.stockLevel];
                doc.setFillColor(...dotColor);
                doc.circle(data.cell.x + 3, data.cell.y + data.cell.height / 2, 1.1, 'F');
                doc.setFont('helvetica', 'normal');
                doc.setFontSize(7.5);
                doc.setTextColor(...COLOR.body);
                doc.text(row.stockLevel, data.cell.x + 6, data.cell.y + data.cell.height / 2 + 1);
            }
            if (data.column.index === 8) {
                const isActive = row.status === 'Active';
                const bg = isActive ? [220, 252, 231] : [241, 245, 249];
                const text = isActive ? [22, 163, 74] : [100, 116, 139];
                const pillWidth = doc.getTextWidth(row.status) + 6;
                doc.setFillColor(bg[0], bg[1], bg[2]);
                doc.roundedRect(data.cell.x + 1.5, data.cell.y + data.cell.height / 2 - 3, pillWidth, 6, 3, 3, 'F');
                doc.setFont('helvetica', 'bold');
                doc.setFontSize(7.5);
                doc.setTextColor(text[0], text[1], text[2]);
                doc.text(row.status, data.cell.x + 1.5 + pillWidth / 2, data.cell.y + data.cell.height / 2 + 1, { align: 'center' });
            }
        },
        // No didDrawPage page-number stamp here on purpose - the final loop below already
        // walks every page (via doc.getNumberOfPages()) and stamps "Page X of Y" once each.
        // Drawing a bare "Page N" here too, then drawing over it later, doesn't erase the
        // first draw (jsPDF has no "clear text" - it just layers glyphs), so the two stamps
        // visually merged into garbled overlapping text.
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = ((doc as any).lastAutoTable?.finalY ?? y + 40) + 8;

    // If the table pushed close to the bottom, the summary/notes below need a fresh page
    // rather than being squeezed into (or spilling past) whatever room is left.
    if (y > PAGE_HEIGHT - 70) {
        doc.addPage();
        y = 20;
    }

    // ---- Summary stats bar: Total Items / Total Current Stock / Total Stock Value ----
    const totalCurrentStock = rows.reduce((sum, row) => sum + row.currentStock, 0);
    const totalStockValue = rows.reduce((sum, row) => sum + (row.stockValue ?? 0), 0);
    const statBoxHeight = 20;
    doc.setDrawColor(...COLOR.border);
    doc.setLineWidth(0.2);
    doc.roundedRect(MARGIN, y, CONTENT_WIDTH, statBoxHeight, 2, 2, 'S');
    const stats: [string, string][] = [
        ['TOTAL ITEMS', String(totalItems)],
        ['TOTAL CURRENT STOCK', totalCurrentStock.toLocaleString('en-IN')],
        ['TOTAL STOCK VALUE', formatRupees(totalStockValue)],
    ];
    const statColWidth = CONTENT_WIDTH / 3;
    stats.forEach(([label, value], index) => {
        const statX = MARGIN + index * statColWidth + 6;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7.5);
        doc.setTextColor(...COLOR.label);
        doc.text(label, statX, y + 8);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(13);
        doc.setTextColor(...COLOR.navy);
        doc.text(value, statX, y + 16);
        if (index > 0) {
            doc.setDrawColor(...COLOR.border);
            doc.line(MARGIN + index * statColWidth, y + 4, MARGIN + index * statColWidth, y + statBoxHeight - 4);
        }
    });
    y += statBoxHeight + 10;

    // ---- Notes ----
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...COLOR.blue);
    doc.text('NOTE:', MARGIN, y);
    y += 6;
    const notes = [
        'Stock levels are calculated based on current warehouse inventory.',
        'Stock Level: Low = at/below Reorder Level (or Min Stock), Good = at/above Max Stock, Medium = in between.',
        'This report is system generated and does not require a signature.',
    ];
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...COLOR.body);
    notes.forEach((note) => {
        doc.text('•', MARGIN, y);
        const lines = doc.splitTextToSize(note, CONTENT_WIDTH - 20);
        doc.text(lines, MARGIN + 5, y);
        y += lines.length * 4.6 + 2;
    });
    // ---- Footer: "Generated By" (left) and "Page X of Y" (right), pinned to the exact same
    // FOOTER_TEXT_Y baseline on every page - previously "Generated By" could drift downward
    // on longer content while the page-number stamp stayed at a different fixed y, so the two
    // didn't align (and could overlap on pages where notes ran long). The divider still falls
    // back to flowing right after the notes (Math.max) on the rare page where content runs
    // past the anchor, and the page-number loop below always mirrors that same y so the two
    // texts stay on one line together regardless.
    const footerDividerY = Math.max(FOOTER_TEXT_Y - 6, y + 4);
    doc.setDrawColor(...COLOR.border);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, footerDividerY, RIGHT_EDGE, footerDividerY);
    const footerY = footerDividerY + 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...COLOR.body);
    // A trailing space inside the string passed to doc.text() isn't reliably measured/kept by
    // jsPDF, so "Generated By: " + name rendered with no visible gap - an explicit +2mm offset
    // after the label's own (space-free) width guarantees the gap actually shows up.
    const generatedByLabel = 'Generated By:';
    doc.text(generatedByLabel, MARGIN, footerY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLOR.muted);
    doc.text(`${companySettings?.companyName ?? 'Inventory'} Management System`, MARGIN + doc.getTextWidth(generatedByLabel) + 2, footerY);

    // Stamp "Page X of Y" on every page now that the total page count is known - same footerY
    // baseline as "Generated By" above, so the two are always on one line together.
    const totalPages = doc.getNumberOfPages();
    for (let page = 1; page <= totalPages; page++) {
        doc.setPage(page);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...COLOR.muted);
        doc.text(`Page ${page} of ${totalPages}`, RIGHT_EDGE, footerY, { align: 'right' });
    }

    doc.save('inventory-report.pdf');
}
