import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { drawPdfLogo, getLogoRenderedHeight, trimTransparentLogoPadding } from './pdfLogo';

const COLOR = {
    navy: [15, 23, 42] as const,
    blue: [37, 99, 235] as const,
    label: [100, 116, 139] as const,
    body: [51, 65, 85] as const,
    muted: [148, 163, 184] as const,
    border: [226, 232, 240] as const,
    surface: [248, 250, 252] as const,
};

const MARGIN = 14;
const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const RIGHT_EDGE = PAGE_WIDTH - MARGIN;
const CONTENT_WIDTH = RIGHT_EDGE - MARGIN;
// Same shared baseline trick as inventoryReportPdf.ts - keeps "Generated By" and "Page X of Y"
// pinned to the exact same row on every page instead of drifting apart.
const FOOTER_TEXT_Y = PAGE_HEIGHT - 14;

export interface ReportPdfCompanySettings {
    companyName: string;
    address: string;
}

// Generic "export a filtered table" PDF, shared by every report tab in Reports.tsx except
// Stock Summary (which gets its own richer layout - see inventoryReportPdf.ts) - mirrors CRM's
// crmReportPdf.ts, which does the same thing for the CRM Leads report. Header/footer design
// (logo-trim, stacked logo+company block, right-aligned title/date, "Generated By"/"Page X of
// Y" footer) intentionally matches inventoryReportPdf.ts's so every exported report in the app
// looks like it came from the same document family, not two different generators.
export async function exportReportPdf(
    title: string,
    filterSummary: string,
    head: string[],
    rows: (string | number)[][],
    filename: string,
    logoDataUrl?: string | null,
    companySettings?: ReportPdfCompanySettings,
): Promise<void> {
    // Trimmed once up front so both the image draw and the height math below agree on the
    // same (padding-free) logo - see trimTransparentLogoPadding for why this is needed.
    const trimmedLogoDataUrl = logoDataUrl ? await trimTransparentLogoPadding(logoDataUrl) : logoDataUrl;
    const doc = new jsPDF();

    // ---- Header: logo (top-left) with company name/address stacked directly BELOW it -
    // title + "Generated" date on the right. ----
    const logoTop = 12;
    const logoMaxSize = 28;
    const logoWidth = drawPdfLogo(doc, trimmedLogoDataUrl, MARGIN, logoTop, logoMaxSize);
    const logoHeight = getLogoRenderedHeight(doc, trimmedLogoDataUrl, logoMaxSize);

    let leftY = logoTop + (logoWidth ? logoHeight + 10 : 0);
    if (companySettings?.companyName) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        doc.setTextColor(...COLOR.navy);
        doc.text(companySettings.companyName, MARGIN, leftY);
        leftY += 5;
    }
    if (companySettings?.address) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(...COLOR.muted);
        const addrLines = doc.splitTextToSize(companySettings.address, CONTENT_WIDTH / 2);
        doc.text(addrLines, MARGIN, leftY);
        leftY += addrLines.length * 4;
    }

    let y = 20;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(...COLOR.blue);
    doc.text(title.toUpperCase(), RIGHT_EDGE, y, { align: 'right' });

    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...COLOR.label);
    doc.text(`Generated ${new Date().toLocaleString('en-IN')}`, RIGHT_EDGE, y, { align: 'right' });

    if (filterSummary) {
        y += 5.5;
        doc.text(filterSummary, RIGHT_EDGE, y, { align: 'right' });
    }

    y = Math.max(leftY, y) + 8;
    doc.setDrawColor(...COLOR.border);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, RIGHT_EDGE, y);
    y += 10;

    // ---- Data table ----
    autoTable(doc, {
        startY: y,
        margin: { left: MARGIN, right: MARGIN, bottom: 20 },
        head: [head],
        body: rows,
        theme: 'plain',
        styles: { fontSize: 8.5, textColor: [...COLOR.body], cellPadding: { top: 3, bottom: 3, left: 2.5, right: 2.5 }, valign: 'middle' },
        headStyles: {
            fillColor: [...COLOR.surface],
            textColor: [...COLOR.navy],
            fontStyle: 'bold',
            fontSize: 8,
            lineWidth: { bottom: 0.3 },
            lineColor: [...COLOR.border],
        },
        bodyStyles: { lineWidth: { bottom: 0.1 }, lineColor: [...COLOR.border] },
        // No didDrawPage page-number stamp here on purpose - the final loop below already
        // walks every page and stamps "Page X of Y" once each (see inventoryReportPdf.ts for
        // why drawing it twice would produce garbled overlapping text).
    });

    // ---- Footer: "Generated By" (left) and "Page X of Y" (right), pinned to the same
    // FOOTER_TEXT_Y baseline on every page. ----
    const footerDividerY = FOOTER_TEXT_Y - 6;
    doc.setDrawColor(...COLOR.border);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, footerDividerY, RIGHT_EDGE, footerDividerY);
    const footerY = footerDividerY + 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...COLOR.body);
    // A trailing space inside the string passed to doc.text() isn't reliably measured/kept by
    // jsPDF, so "Generated By: " + name rendered with no visible gap - an explicit +2mm offset
    // after the label's own (space-free) width guarantees the gap actually shows up.
    const generatedByLabel = 'Generated By:';
    doc.text(generatedByLabel, MARGIN, footerY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLOR.muted);
    doc.text(`${companySettings?.companyName ?? 'Inventory'} Management System`, MARGIN + doc.getTextWidth(generatedByLabel) + 2, footerY);

    // Stamp "Page X of Y" on every page now that the total page count is known - same footerY
    // baseline as "Generated By" above, so the two are always on one line together.
    const totalPages = doc.getNumberOfPages();
    for (let page = 1; page <= totalPages; page++) {
        doc.setPage(page);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...COLOR.muted);
        doc.text(`Page ${page} of ${totalPages}`, RIGHT_EDGE, footerY, { align: 'right' });
    }

    doc.save(filename);
}
